# Generated by Django 4.1.4 on 2023-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='username',
        ),
        migrations.AddField(
            model_name='seller',
            name='merchantId',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='seller',
            name='pdtToken',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
